import React from "react";
import Blog from '../blog';
import Container from 'react-bootstrap/Container'

function Listblogs(){
    return(
        <Container className="page-begins">
        <h1 className="superheading centerstuff">
            Blogs
        </h1>
        <Blog 
        title="Lorem Ipsum"
        subtitle="Dolor sit amet"
        p1 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eget velit aliquet sagittis id. Neque convallis a cras semper. Vivamus at augue eget arcu. Viverra ipsum nunc aliquet bibendum enim facilisis. At elementum eu facilisis sed odio. Tellus in metus vulputate eu scelerisque felis imperdiet proin. Urna cursus eget nunc scelerisque viverra mauris in aliquam. Aliquam nulla facilisi cras fermentum odio. Ac turpis egestas sed tempus urna. Leo duis ut diam quam nulla porttitor massa. Morbi tristique senectus et netus et. Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Cras tincidunt lobortis feugiat vivamus at. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Senectus et netus et malesuada. Vulputate odio ut enim blandit volutpat maecenas. Neque gravida in fermentum et. Ornare aenean euismod elementum nisi quis eleifend quam."
        p2 = "Consectetur libero id faucibus nisl tincidunt eget. Eget nunc lobortis mattis aliquam. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien. Id interdum velit laoreet id. Massa ultricies mi quis hendrerit. Quisque non tellus orci ac auctor augue mauris augue. Phasellus faucibus scelerisque eleifend donec. Et pharetra pharetra massa massa. Nullam eget felis eget nunc lobortis. Erat imperdiet sed euismod nisi. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum. Diam vulputate ut pharetra sit amet. Molestie a iaculis at erat. Nunc lobortis mattis aliquam faucibus purus in massa. Mattis pellentesque id nibh tortor id aliquet lectus proin. Scelerisque in dictum non consectetur a erat nam at. Fusce id velit ut tortor pretium viverra suspendisse potenti. Cursus vitae congue mauris rhoncus aenean."
        p3 = "Mattis pellentesque id nibh tortor id aliquet lectus proin nibh. Morbi tempus iaculis urna id volutpat. Sed cras ornare arcu dui vivamus arcu. Egestas maecenas pharetra convallis posuere morbi leo urna molestie at. Arcu felis bibendum ut tristique et egestas quis ipsum. Tortor at risus viverra adipiscing at in tellus integer feugiat. Ipsum suspendisse ultrices gravida dictum fusce ut. Tristique et egestas quis ipsum suspendisse ultrices gravida. Eu lobortis elementum nibh tellus molestie nunc non. Pulvinar pellentesque habitant morbi tristique senectus. Elementum nisi quis eleifend quam adipiscing. Purus gravida quis blandit turpis cursus in hac habitasse. Vel elit scelerisque mauris pellentesque pulvinar."
        p4 = "Enim nunc faucibus a pellentesque sit amet porttitor eget. Quam viverra orci sagittis eu volutpat odio facilisis mauris. Suspendisse faucibus interdum posuere lorem ipsum dolor. Vitae sapien pellentesque habitant morbi tristique senectus et netus et. Donec adipiscing tristique risus nec. Enim blandit volutpat maecenas volutpat blandit aliquam etiam erat velit. Habitasse platea dictumst quisque sagittis purus sit amet volutpat. Justo nec ultrices dui sapien eget mi proin sed. Laoreet non curabitur gravida arcu ac tortor dignissim. Amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. Ornare lectus sit amet est placerat in egestas erat. Mattis nunc sed blandit libero volutpat sed cras. Fames ac turpis egestas maecenas pharetra convallis posuere morbi leo. Vitae congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Ac placerat vestibulum lectus mauris. Nisl nisi scelerisque eu ultrices vitae auctor eu augue. Vulputate enim nulla aliquet porttitor lacus luctus. Praesent elementum facilisis leo vel fringilla est. Egestas tellus rutrum tellus pellentesque eu tincidunt tortor. Leo vel orci porta non."
        p5 = "Turpis egestas integer eget aliquet nibh praesent tristique magna sit. Mi bibendum neque egestas congue quisque. Quam vulputate dignissim suspendisse in est ante in nibh mauris. Pellentesque eu tincidunt tortor aliquam nulla facilisi. Consectetur adipiscing elit pellentesque habitant. Nisi vitae suscipit tellus mauris a diam. Iaculis urna id volutpat lacus laoreet non. Ornare lectus sit amet est placerat in egestas. Ut sem nulla pharetra diam sit amet nisl suscipit adipiscing. Eu non diam phasellus vestibulum lorem sed risus ultricies. Eget arcu dictum varius duis at consectetur lorem donec massa. Nunc eget lorem dolor sed viverra ipsum nunc aliquet bibendum. Nulla pellentesque dignissim enim sit. Blandit cursus risus at ultrices mi tempus imperdiet nulla. Enim sit amet venenatis urna cursus. Platea dictumst vestibulum rhoncus est."
        author = "Urna Semper"
        />
        <Blog 
        title="Lorem Ipsum"
        subtitle="Dolor sit amet"
        p1 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eget velit aliquet sagittis id. Neque convallis a cras semper. Vivamus at augue eget arcu. Viverra ipsum nunc aliquet bibendum enim facilisis. At elementum eu facilisis sed odio. Tellus in metus vulputate eu scelerisque felis imperdiet proin. Urna cursus eget nunc scelerisque viverra mauris in aliquam. Aliquam nulla facilisi cras fermentum odio. Ac turpis egestas sed tempus urna. Leo duis ut diam quam nulla porttitor massa. Morbi tristique senectus et netus et. Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam nulla. Cras tincidunt lobortis feugiat vivamus at. Nulla facilisi nullam vehicula ipsum a arcu cursus vitae. Senectus et netus et malesuada. Vulputate odio ut enim blandit volutpat maecenas. Neque gravida in fermentum et. Ornare aenean euismod elementum nisi quis eleifend quam."
        p2 = "Consectetur libero id faucibus nisl tincidunt eget. Eget nunc lobortis mattis aliquam. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien. Id interdum velit laoreet id. Massa ultricies mi quis hendrerit. Quisque non tellus orci ac auctor augue mauris augue. Phasellus faucibus scelerisque eleifend donec. Et pharetra pharetra massa massa. Nullam eget felis eget nunc lobortis. Erat imperdiet sed euismod nisi. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum. Diam vulputate ut pharetra sit amet. Molestie a iaculis at erat. Nunc lobortis mattis aliquam faucibus purus in massa. Mattis pellentesque id nibh tortor id aliquet lectus proin. Scelerisque in dictum non consectetur a erat nam at. Fusce id velit ut tortor pretium viverra suspendisse potenti. Cursus vitae congue mauris rhoncus aenean."
        p3 = "Mattis pellentesque id nibh tortor id aliquet lectus proin nibh. Morbi tempus iaculis urna id volutpat. Sed cras ornare arcu dui vivamus arcu. Egestas maecenas pharetra convallis posuere morbi leo urna molestie at. Arcu felis bibendum ut tristique et egestas quis ipsum. Tortor at risus viverra adipiscing at in tellus integer feugiat. Ipsum suspendisse ultrices gravida dictum fusce ut. Tristique et egestas quis ipsum suspendisse ultrices gravida. Eu lobortis elementum nibh tellus molestie nunc non. Pulvinar pellentesque habitant morbi tristique senectus. Elementum nisi quis eleifend quam adipiscing. Purus gravida quis blandit turpis cursus in hac habitasse. Vel elit scelerisque mauris pellentesque pulvinar."
        p4 = "Enim nunc faucibus a pellentesque sit amet porttitor eget. Quam viverra orci sagittis eu volutpat odio facilisis mauris. Suspendisse faucibus interdum posuere lorem ipsum dolor. Vitae sapien pellentesque habitant morbi tristique senectus et netus et. Donec adipiscing tristique risus nec. Enim blandit volutpat maecenas volutpat blandit aliquam etiam erat velit. Habitasse platea dictumst quisque sagittis purus sit amet volutpat. Justo nec ultrices dui sapien eget mi proin sed. Laoreet non curabitur gravida arcu ac tortor dignissim. Amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. Ornare lectus sit amet est placerat in egestas erat. Mattis nunc sed blandit libero volutpat sed cras. Fames ac turpis egestas maecenas pharetra convallis posuere morbi leo. Vitae congue mauris rhoncus aenean vel elit scelerisque mauris pellentesque. Ac placerat vestibulum lectus mauris. Nisl nisi scelerisque eu ultrices vitae auctor eu augue. Vulputate enim nulla aliquet porttitor lacus luctus. Praesent elementum facilisis leo vel fringilla est. Egestas tellus rutrum tellus pellentesque eu tincidunt tortor. Leo vel orci porta non."
        p5 = "Turpis egestas integer eget aliquet nibh praesent tristique magna sit. Mi bibendum neque egestas congue quisque. Quam vulputate dignissim suspendisse in est ante in nibh mauris. Pellentesque eu tincidunt tortor aliquam nulla facilisi. Consectetur adipiscing elit pellentesque habitant. Nisi vitae suscipit tellus mauris a diam. Iaculis urna id volutpat lacus laoreet non. Ornare lectus sit amet est placerat in egestas. Ut sem nulla pharetra diam sit amet nisl suscipit adipiscing. Eu non diam phasellus vestibulum lorem sed risus ultricies. Eget arcu dictum varius duis at consectetur lorem donec massa. Nunc eget lorem dolor sed viverra ipsum nunc aliquet bibendum. Nulla pellentesque dignissim enim sit. Blandit cursus risus at ultrices mi tempus imperdiet nulla. Enim sit amet venenatis urna cursus. Platea dictumst vestibulum rhoncus est."
        author = "Urna Semper"
        />
        </Container>
        
    );
}

export default Listblogs;